#ifndef SYSTEM_EVENT_H
#define SYSTEM_EVENT_H

typedef enum{
    EVENT_SYSTEM_ENABLE,
    EVENT_SYSTEM_DISABLE,
    EVENT_VEHICLE_DETECTED,
    EVENT_PIN_VALID,
    EVENT_PIN_INVALID,
    EVENT_BARRIER_OPENED,
    EVENT_VEHICLE_PASSED,
    EVENT_BARRIER_CLOSED,
    EVENT_LOT_FULL,
    EVENT_SPACE_AVAILABLE,
    EVENT_ALARM_TRIGGERED,
    EVENT_ALARM_RESET,
    EVENT_EMERGENCY_ON,
    EVENT_EMERGENCY_OFF
}system_event_type_t;

#endif
